language: java

matrix:
  allow_failures:
    - os: linux
  include:
    - os: linux
      sudo: true
      jdk: oraclejdk8
    - os: linux
      sudo: true
      jdk: oraclejdk7
    - os: osx
      osx_image: xcode7.2
    - os: osx
      osx_image: xcode8.3

before_install:
  - ./travis/setup_$TRAVIS_OS_NAME.sh

script:
  - ./gradlew check --stacktrace --info

env:
    global:
        - CI=true
        - CI_NAME=travis-ci

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/Library/Caches/Homebrew
    - $HOME/.travis_linux

after_script:
  - ./travis/after_$TRAVIS_OS_NAME.sh

after_success:
- ./gradlew jacocoTestReport coveralls
